---

- name: "download docker"
  become: yes
  shell: |
    apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release 
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "install docker"
  become: yes
  shell: |
    apt install docker-ce docker-ce-cli containerd.io -y
    chmod 666 /var/run/docker.sock

- name: "install minicube & kubectl"
  become: yes
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
